apiVersion: batch/v1
kind: Job
metadata:
  name: build
spec:
  template:
    spec:
      containers:
      - name: build
        image: openjdk:8
        command: ["bash",  "-ec",
                  "mkdir -p /tmp/build && cd /tmp/build
                  && git clone https://github.com/faficode/JenkinsMonitoring-Showcase.git
                  && cd JenkinsMonitoring-Showcase
                  && cd apps/simple
                  && ./gradlew distZip
                  && curl -XPOST --data-binary @build/distributions/simple.zip http://repo/simple.zip"]
      restartPolicy: Never
