apiVersion: v1
kind: Service
metadata:
  name: elastic
spec:
  selector:
    app: elastic
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elastic
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  serviceName: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      enableServiceLinks: false
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
          name: elastic
          ports:
            - containerPort: 9200
          env:
            - name: "discovery.type"
              value: "single-node"