apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      name: 'internal'
      port: 9092
      targetPort: 9092
    - protocol: TCP
      name: 'external'
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - image: confluentinc/cp-kafka:5.2.4
          name: kafka
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo:2881
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,CLUSTER:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka:9091,CLUSTER://kafka:9092"
#            - name: KAFKA_BROKER_ID_GENERATION_ENABLE
#              value: false
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms1000M -Xmx1000M"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
