apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    app: simple-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-app
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - image: openjdk:8
        name: app
        ports:
        - containerPort: 8080
        command: ["bash", "-ec", "cd /opt
          && curl -O http://repo/simple.zip && unzip simple.zip
          && ./simple/bin/simple"]